Widespread changes for showing this year's schedule skeleton 📅
code4lib/2024.code4lib.org pull request #24
Opened 2023-11-06 19:51 UTC by triplingual

Many details needed to be changed to accommodate the workshops being at the end, including day numbering, as we agreed 
(https://code4lib.slack.com/archives/C0D9KS1EU/p1699039447250239) that we would move to 1-based indexing. To reinforce this, I chose to add a dummy date to _data/conf.yml so any indexes in templates/variables could sync with the day of the conference. Open to other ideas.

Closes #20, #21

2023-11-06 19:53 UTC, escowles commented on general-info/first-timers.html
> +        We have a packed program with talks, lightning talks, breakout sessions, and post-conferences.
Do we want to call them "workshops" or something that doesn't change for pre vs. post?

2023-11-06 19:54 UTC, triplingual commented
Review-request spam is because there were a bunch of items changed to make this happen, and I'm green enough that I'm nervous about putting a faulty sked out there, or one that didn't account for all the downstream effects.

2023-11-06 19:54 UTC, triplingual commented on general-info/first-timers.html
> +        We have a packed program with talks, lightning talks, breakout sessions, and post-conferences.
Ooh, good idea.

2023-11-06 19:55 UTC, escowles commented on schedule/food/day1-menus.html
> +backlink: "/schedule/day-0"
I don't understand why `day1-menus.html` is now referencing `day0`

2023-11-06 20:02 UTC, triplingual commented on schedule/food/day1-menus.html
> +backlink: "/schedule/day-0"
Probably just missed that one.

2023-11-06 22:10 UTC, phette23 commented on general-info/venues/workshops.html
> +            All workshops will be held {{ site.data.conf.days[3].weekday }}, {{ site.data.conf.days[3].date-data | date: "%B %-d, %Y" }}{% if location %} in <a href="{{ location.google_maps }}">{{ lo
This should be `site.data.conf.days[4]` because of the new numbering scheme (not off by 1)

2023-11-06 22:15 UTC, phette23 commented on schedule/index.html
> +            <h3>1PM to 5:30PM
Do we know that the first day is going to be an afternoon half day like this? I think that tracks with past conferences where the last day was a half-day in the morning but I just hadn't heard.

2023-11-06 22:38 UTC, phette23 commented on schedule/food/day1-menus.html
> +backlink: "/schedule/day-0"
Yeah I think all the dayX-menus.html pages should reference the same day number like

```
title: Day 2 Menus
menu: day2-menus
backlink: "/schedule/day-2"
backlink_text: Day 2
```

Right now, if you turn on menu links, copy the example menu into _data, and visit it, the backlink won't work right because it's pointing to a day earlier.

2023-11-06 22:47 UTC, phette23 requested changes
This looks great! That was a lot of values to update across the site. The menus and venues/workshops.html need changes is all.

2023-11-07 12:51 UTC, triplingual commented on schedule/index.html
> +            <h3>1PM to 5:30PM
Def. Message from Kathy Acevedo in a Slack thread: https://code4lib.slack.com/archives/C1AJTFDMF/p1699035992623309?thread_ts=1699032982.224099&cid=C1AJTFDMF

2023-11-07 13:03 UTC, triplingual commented on schedule/food/day1-menus.html
> +backlink: "/schedule/day-0"
Addressed

2023-11-07 13:08 UTC, triplingual commented on general-info/venues/workshops.html
> +            All workshops will be held {{ site.data.conf.days[3].weekday }}, {{ site.data.conf.days[3].date-data | date: "%B %-d, %Y" }}{% if location %} in <a href="{{ location.google_maps }}">{{ lo
Good catch! Addressed in ca1dbb1.

2023-11-07 15:39 UTC, escowles approved these changes

2023-11-07 16:26 UTC, phette23 approved these changes

2023-11-07 16:26 UTC, merged